// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bento: dynamic(() => import("./Bento")),
  bsv_code_hero: dynamic(() => import("./BsvCodeHero")),
  portifolio: dynamic(() => import("./Portifolio")),
  projeto_slices: dynamic(() => import("./ProjetoSlices")),
  richt_text: dynamic(() => import("./RichtText")),
  showcase: dynamic(() => import("./Showcase")),
  teste: dynamic(() => import("./Teste")),
};
